### ISSUE TITLE
Misc fixes from 13.10.2017

### ISSUE THREAD

**Issue by Mikanebu** [datasets/employment-us#7]
We want to have our dataset whole and accurate

## Acceptance criteria 

* [x] Showcase page has 2 graphs
* [x] `Readme` is live 
* [x] `datapackage.json` is fixed
  * [x] rename `name` property to `employment-us`
  * [x] move `author` and `maintainer` into `contributors`
  * [x] fix typo in data, cse header `uneployed_percent` 

## Tasks

* [x] `datapackage.json`
  * [x] rename `name` property to `employment-us`
  * [x] move `author` and `maintainer` into `contributors`
  * [x] fix typo in data, cse header `uneployed_percent`
  * [x] add graph with the column `unemployment_percent`
  * [x] add `resources/sources` with the `sources_link: ftp...`
  * [x] check `readme` is showing on showcase page
  * [x] remove empty properties

**Comment by Mikanebu** [comment]
FIXED, `datapackage.json` updated, readme and graphs, table are live on datahub.io
